on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

name: pre-commit-checks

permissions:
  id-token: write
  contents: read

jobs:
  call-pre-commit-checks:
    uses: maksystem-platform/workflows/.github/workflows/pre-commit-checks.yaml@main
    secrets: inherit
    with:
      pre-commit-config-file: ".pre-commit-config-validate-folder.yaml"
