on:
  push

name: tag-and-release

permissions:
  id-token: write
  contents: read

env:
  TOOLS_BASE: .github/scripts
  GITHUB_USER_TOKEN: ${{ secrets.LZ_DEVOPS_WORKFLOW_PAT }}
  GITHUB_USER_EMAIL: c.funderburg@mak-system.net
  GITHUB_USER_NAME: bocan

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code (maksystem-platform/workflows)
        uses: actions/checkout@v4
        with:
          token: ${{ env.GITHUB_USER_TOKEN }}
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        id: tag
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_USER_TOKEN }}
          WITH_V: true
          PRERELEASE: false
          RELEASE_BRANCHES: main,CLOUD-710
      - name: Tag and Create a Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ env.GITHUB_USER_TOKEN }}
          tag_name: ${{ steps.tag.outputs.new_tag }}
          generate_release_notes: true
          make_latest: true
